### ISSUE TITLE
naming convention cua chu tut xam lz qua, ko bit noi gi

### ISSUE THREAD

**Issue by nguyenvanhoangnhan** [hungsvdut2k2/PBL3#3]

**Comment by letronghoangminh** [comment]
![image](https://user-images.githubusercontent.com/50044415/169943687-f35a01f0-d254-4a5e-b6cb-24b6353af50a.png)

**Comment by letronghoangminh** [comment]
![image](https://user-images.githubusercontent.com/50044415/169943771-d8907c0a-c726-4f7b-b2cf-8b4b762836ca.png)
